export enum AddToCartStatus {
  SUCCESS = 'SUCCESS',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  QUANTITY_LIMIT_REACHED = 'QUANTITY_LIMIT_REACHED',
  PRODUCT_DOES_NOT_EXIST = 'PRODUCT_DOES_NOT_EXIST',
  API_ERROR = 'API_ERROR',
  INVALID_QUANTITY = 'INVALID_QUANTITY' // Quantidade selecionada é inválida (ex: <= 0)
}
